name: food_api
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  http: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
